# SPDX-License-Identifier: Apache-2.0

repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.11.5
      hooks:
          - id: isort
            exclude: imports
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.5.0
      hooks:
        # Run the linter (most fixers are disabled for now).
        - id: ruff
        # Run the formatter.
        - id: ruff-format
