# SPDX-FileCopyrightText: The InstructLab Authors
# SPDX-License-Identifier: Apache-2.0

repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            exclude: imports
    - repo: https://github.com/PyCQA/isort
      rev: 5.11.5
      hooks:
          - id: isort
            exclude: imports
