# SPDX-License-Identifier: Apache-2.0

name: Test build cuda container image

on:
  push:
    branches:
      - main
    paths:
      - 'containers/cuda/Containerfile'
      - '.github/workflows/image-cuda.yml' # This workflow
  pull_request:
    branches:
      - main
    paths:
      - 'containers/cuda/Containerfile'
      - '.github/workflows/image-cuda.yml' # This workflow

# Note that the current containerfile builds against a git ref.
# It is not built against the current source tree. So, we test
# build the image against `main` if the file changes.
jobs:
  build_cuda_image_main:
    name: Build CUDA image for main
    runs-on: ubuntu-latest
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Free disk space
        run: |
          df -h
          sudo docker rmi "$(docker image ls -aq)" >/dev/null 2>&1 || true
          sudo rm -rf \
            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
            /usr/lib/jvm || true
          sudo apt install aptitude -y >/dev/null 2>&1
          sudo aptitude purge '~n ^mysql' -f -y >/dev/null 2>&1
          sudo aptitude purge '~n ^dotnet' -f -y >/dev/null 2>&1
          sudo apt-get autoremove -y >/dev/null 2>&1
          sudo apt-get autoclean -y >/dev/null 2>&1
          df -h

      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependent PRs if needed
        uses: depends-on/depends-on-action@61cb3f4a0e2c8ae4b90c9448dc57c7ba9ca24c35 # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Extract metadata (tags, labels) for gotbot image
        id: gobot_meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            ghcr.io/${{ github.repository }}/instructlab-cuda

      - name: Build and push gobot image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            GIT_TAG=main
          push: false
          tags: ${{ steps.gobot_meta.outputs.tags }}
          labels: ${{ steps.gobot_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: containers/cuda/Containerfile
